# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x07\n\x05\x45mpty\"\x1e\n\tHeartbeat\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1b\n\x0bStateUpdate\x12\x0c\n\x04test\x18\x01 \x01(\t2z\n\x0eReplicaService\x12\x35\n\x11StateUpdateStream\x12\x0b.chat.Empty\x1a\x11.chat.StateUpdate0\x01\x12\x31\n\x0fHeartbeatStream\x12\x0b.chat.Empty\x1a\x0f.chat.Heartbeat0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _HEARTBEAT._serialized_start=29
  _HEARTBEAT._serialized_end=59
  _STATEUPDATE._serialized_start=61
  _STATEUPDATE._serialized_end=88
  _REPLICASERVICE._serialized_start=90
  _REPLICASERVICE._serialized_end=212
# @@protoc_insertion_point(module_scope)
